### ISSUE TITLE
Documentation on operatorhub.io is incomplete

### ISSUE THREAD

**Issue by bryonbaker** [openshift/kubefed-operator#55]
The documentation makes no mention that you need to deploy the control plane.
It needs something like the following:
Now we need to create a KubeFed resource to instantiate the KubeFed Controller in cluster scoped mode:
```
cat <<-EOF | oc apply -n <namespace> -f -
---
apiVersion: operator.kubefed.io/v1alpha1
kind: KubeFed
metadata:
  name: kubefed-resource
spec:
  scope: Cluster
---
EOF
```

**Comment by bryonbaker** [comment]
Closing the issue as I should have raised this in the documentation repo...

**Comment by marun** [comment]
It appears there is mention of this requirement in the README for the repo (i.e. `kubectl create -f deploy/crds/operator_v1alpha1_kubefed_cr.yaml -n kubefed-test`), and if that detail is missing from the operator docs that is definitely an oversight.

**Comment by sohankunkerkar** [comment]
@bryonbaker We're working on updating the documentation for kubefed-operator on `operatorhub.io`. You can track this PR #43 for more details.
