### ISSUE TITLE
KubeFed controller-manager fails to boot - Error: invalid KubeFedConfig

### ISSUE THREAD

**Issue by Kiran01bm** [openshift/kubefed-operator#74]
## Summary
I'm trying to deploy Kubefed Operator - 0.1.0. The kubefed-controller-manager fails to boot with the following error:

## Error Message:
Error: invalid KubeFedConfig "test-namespace/kubefed": [spec.controllerDuration: Required value spec.leaderElect: Required value spec.featureGates: Required value spec.clusterHealthCheck: Required value spec.syncController: Required value]

## Logs Below:
```
KubeFed controller-manager version: version.Info{Version:"v0.1.0-rc6", GitCommit:"7586b42f4f477f1912caf28287fa2e0a7f68f407", GitTreeState:"clean", BuildDate:"2019-08-17T02:48:03Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
W0906 02:07:16.488353       1 client_config.go:549] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0906 02:07:16.889052       1 controller-manager.go:224] Setting Options with KubeFedConfig "test-namespace/kubefed"
F0906 02:07:16.889089       1 controller-manager.go:313] Error: invalid KubeFedConfig "test-namespace/kubefed": [spec.controllerDuration: Required value spec.leaderElect: Required value spec.featureGates: Required value spec.clusterHealthCheck: Required value spec.syncController: Required value]
```

## More info:
I found the upstream [kubefed config here](https://github.com/kubernetes-sigs/kubefed/blob/master/example/config/kubefedconfig.yaml) but that too does not have syncController or clusterHealthCheck. I've also looked at [controller-manager.go]( https://github.com/kubernetes-sigs/kubefed/blob/master/cmd/controller-manager/app/controller-manager.go) but would like to get a example config that works.

**Comment by Kiran01bm** [comment]
The following Kubefedconfig contains all the required fields and worked fine.
```
apiVersion: core.kubefed.io/v1beta1
kind: KubeFedConfig
metadata:
  name: kubefed
  namespace: kube-federation-system
spec:
  scope: Cluster
  syncController:
    adoptResources: Enabled
  clusterHealthCheck:
    failureThreshold: 5
    period: 20s
    successThreshold: 1
    timeout: 10s
  controllerDuration:
    availableDelay: 20s
    unavailableDelay: 60s
    clusterMonitorPeriod: 40s
  leaderElect:
    leaseDuration: 15s
    renewDeadline: 10s
    retryPeriod: 5s
    resourceLock: configmaps
  featureGates:
  - name: PushReconciler
    configuration: "Enabled"
  - name: SchedulerPreferences
    configuration: "Enabled"
  - name: CrossClusterServiceDiscovery
    configuration: "Enabled"
  - name: FederatedIngress
    configuration: "Enabled"
```

**Comment by Kiran01bm** [comment]
Closed accidentally. Re-opening it. So basically the operator needs to be fixed to provision Kubefedconfig with all the required fields.

**Comment by abhat** [comment]
@Kiran01bm are you using the version of the kubefed-operator from operatorhub.io or from under the OKD community operators on the in-cluster operator hub? Is this on openshift/kube?

**Comment by abhat** [comment]
Also, if you are using the operator from under the community operator's catalog source, did you create a KubeFedWebHook CR instance? This will create the admission webhook pod which will mutate the default KubeFedConfig created by the controller-manager to have the required fields populated.

**Comment by Kiran01bm** [comment]
@abhat - Its OCP v4.1, Catalog -> Operator Hub --> KubeFed. So yes, I'm _"using the operator from under the community operator's catalog source"_  and i did not create the KubeFedWebHook CR instance. I now see that the instructions on the Operator page were clear.  So its my fault. I'll try this approach. Thanks for pointing this out.

> You must create the KubeFedWebHook and KubeFed custom resources (CRs) for KubeFed deployment. The operator will create the following CRDs (KubeFedWebHook and KubeFed) automatically for deploying components of a KubeFed control plane

**Comment by abhat** [comment]
@Kiran01bm did you get a chance to try this out? Can we close the issue?

**Comment by Kiran01bm** [comment]
@abhat - yes I did try it out and it works fine. Closing the issue now.

**Comment by Kiran01bm** [comment]
I did not create the KubeFedWebHook CR instance prior to creating the KubeFedConfig.

**Comment by Kiran01bm** [comment]
Cause: I did not create the KubeFedWebHook CR instance prior to creating the KubeFedConfig.
