### ISSUE TITLE
4.3 olm data needs to be updated

### ISSUE THREAD

**Issue by jupierce** [openshift/kubefed-operator#78]
https://github.com/openshift/kubefed-operator/tree/release-4.3/deploy/olm-catalog/kubefed-operator
file does not exist: deploy/olm-catalog/kubefed-operator/4.3/image-references

**Comment by jupierce** [comment]
@sohankunkerkar @abhat

**Comment by sosiouxme** [comment]
https://github.com/openshift/kubefed-operator/pull/82
