### ISSUE TITLE
Please prepare bundle for OCP 4.4

### ISSUE THREAD

**Issue by sosiouxme** [openshift/kubefed-operator#83]
Now that we are fully branched for 4.4, please prepare your operator to supply a 4.4 bundle, so that 4.4 operator publishing works -- unless you don't expect to have kubefed-operator in 4.4?

This means at least updating the package.yaml under https://github.com/openshift/kubefed-operator/tree/master/deploy/olm-catalog/kubefed-operator
@abhat @sohankunkerkar

**Comment by sosiouxme** [comment]
@abhat @sohankunkerkar re-ping on this. You'll come to me wondering why your operator isn't building downstream...

**Comment by sosiouxme** [comment]
Actually the operator is already disabled from building:
https://github.com/openshift/ocp-build-data/blob/openshift-4.4/images/kubefed-operator.yml#L1
and looks like there's not much activity here, so I'll just assume kubefed-operator is defunct until we hear signs of life!

**Comment by abhat** [comment]
Yep, that is a good assumption to make for now.
